### ISSUE TITLE
Slow down you are editing too fast

### ISSUE THREAD

**Issue by Kot1koff** [superisuer/change-tiktok-username-gui#1]
![image](https://github.com/user-attachments/assets/ce792078-4524-4009-bc33-db80e9a46a50)
не удается  сменить юзер

**Comment by Kot1koff** [comment]
на других аккаунтах работает, а на основе такая ошибка

**Comment by superiuser** [comment]
Другой ник попробуй

**Comment by superisuer** [comment]
Попробуй другой ник, другой регион аккаунта. На нынешнее время, ещё неизвестно о данной проблеме. Я постараюсь проверить смену.

**Comment by superisuer** [comment]
**Уже не работает способ.**
